<a href="https://colab.research.google.com/github/pranshurastogi29/clustering-the-palsy/blob/master/stat_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from scipy import stats

df = pd.read_csv('/content/drive/My Drive/cpi.csv')

In [7]:
from math import sqrt
from numpy.random import seed
from numpy.random import randn
from numpy import mean
from scipy.stats import sem
from scipy.stats import t
 
# function for calculating the t-test for two independent samples
def independent_ttest(data1, data2, alpha):
	# calculate means
	mean1, mean2 = mean(data1), mean(data2)
	# calculate standard errors
	se1, se2 = sem(data1), sem(data2)
	# standard error on the difference between the samples
	sed = sqrt(se1**2.0 + se2**2.0)
	# calculate the t statistic
	t_stat = (mean1 - mean2) / sed
	# degrees of freedom
	df = len(data1) + len(data2) - 2
	# calculate the critical value
	cv = t.ppf(1.0 - alpha, df)
	# calculate the p-value
	p = (1.0 - t.cdf(abs(t_stat), df)) * 2.0
	# return everything
	return t_stat, df, cv, p
 
# seed the random number generator
seed(1)
# generate two independent samples
# calculate the t test
d,l = [],[]
for i in df.columns:
  for j in df.columns:
    data1 = df[i].values
    data2 = df[j].values
    alpha = 0.05
    print(i,j)
    t_stat, val, cv, p = independent_ttest(data1, data2, alpha)
    print('t=%.3f, df=%d, cv=%.3f, p=%.3f' % (t_stat, val, cv, p))
    # interpret via critical value
    if abs(t_stat) <= cv:
	    print('Accept null hypothesis that the means are equal.')
    else:
	    print('Reject the null hypothesis that the means are equal.')
    # interpret via p-value
    if p > alpha:
	    print('Accept null hypothesis that the means are equal.')
    else:
	    print('Reject the null hypothesis that the means are equal.')
    l.append(t_stat)
  d.append(l)
  l = []
d = np.array(d)

fcmeans fcmeans
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
fcmeans kmeans
t=2.519, df=30, cv=1.697, p=0.017
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
fcmeans cso_km
t=11.800, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
fcmeans cso_fm
t=9.754, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
fcmeans g_cso_km
t=13.029, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
fcmeans g_cso_fm
t=6.867, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
fcmeans cn_pso
t=0.770, df=30, cv=1.697, p=0.447
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
fcmeans cn_pso_km
t=0.411, df=30, cv=1.697, p=0.684
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
fcmeans cn_pso_fm
t=0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
fcmeans hpso_km
t=0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
fcmeans hpso_fm
t=0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
kmeans fcmeans
t=-2.519, df=30, cv=1.697, p=0.017
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans kmeans
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
kmeans cso_km
t=9.327, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans cso_fm
t=7.571, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans g_cso_km
t=10.268, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans g_cso_fm
t=4.885, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans cn_pso
t=-2.254, df=30, cv=1.697, p=0.032
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans cn_pso_km
t=-3.151, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans cn_pso_fm
t=-3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans hpso_km
t=-3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
kmeans hpso_fm
t=-3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km fcmeans
t=-11.800, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km kmeans
t=-9.327, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km cso_km
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_km cso_fm
t=-0.617, df=30, cv=1.697, p=0.542
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_km g_cso_km
t=-0.197, df=30, cv=1.697, p=0.845
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_km g_cso_fm
t=-2.508, df=30, cv=1.697, p=0.018
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km cn_pso
t=-13.401, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km cn_pso_km
t=-16.241, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km cn_pso_fm
t=-16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km hpso_km
t=-16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_km hpso_fm
t=-16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm fcmeans
t=-9.754, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm kmeans
t=-7.571, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm cso_km
t=0.617, df=30, cv=1.697, p=0.542
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_fm cso_fm
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_fm g_cso_km
t=0.504, df=30, cv=1.697, p=0.618
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_fm g_cso_fm
t=-1.791, df=30, cv=1.697, p=0.083
Reject the null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cso_fm cn_pso
t=-10.520, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm cn_pso_km
t=-12.106, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm cn_pso_fm
t=-12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm hpso_km
t=-12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cso_fm hpso_fm
t=-12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km fcmeans
t=-13.029, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km kmeans
t=-10.268, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km cso_km
t=0.197, df=30, cv=1.697, p=0.845
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
g_cso_km cso_fm
t=-0.504, df=30, cv=1.697, p=0.618
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
g_cso_km g_cso_km
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
g_cso_km g_cso_fm
t=-2.538, df=30, cv=1.697, p=0.017
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km cn_pso
t=-15.703, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km cn_pso_km
t=-20.759, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km cn_pso_fm
t=-20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km hpso_km
t=-20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_km hpso_fm
t=-20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm fcmeans
t=-6.867, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm kmeans
t=-4.885, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm cso_km
t=2.508, df=30, cv=1.697, p=0.018
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm cso_fm
t=1.791, df=30, cv=1.697, p=0.083
Reject the null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
g_cso_fm g_cso_km
t=2.538, df=30, cv=1.697, p=0.017
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm g_cso_fm
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
g_cso_fm cn_pso
t=-7.078, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm cn_pso_km
t=-8.011, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm cn_pso_fm
t=-7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm hpso_km
t=-7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
g_cso_fm hpso_fm
t=-7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso fcmeans
t=-0.770, df=30, cv=1.697, p=0.447
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso kmeans
t=2.254, df=30, cv=1.697, p=0.032
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso cso_km
t=13.401, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso cso_fm
t=10.520, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso g_cso_km
t=15.703, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso g_cso_fm
t=7.078, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso cn_pso
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso cn_pso_km
t=-0.788, df=30, cv=1.697, p=0.437
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso cn_pso_fm
t=-0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso hpso_km
t=-0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso hpso_fm
t=-0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km fcmeans
t=-0.411, df=30, cv=1.697, p=0.684
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km kmeans
t=3.151, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_km cso_km
t=16.241, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_km cso_fm
t=12.106, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_km g_cso_km
t=20.759, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_km g_cso_fm
t=8.011, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_km cn_pso
t=0.788, df=30, cv=1.697, p=0.437
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km cn_pso_km
t=0.000, df=30, cv=1.697, p=1.000
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km cn_pso_fm
t=1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km hpso_km
t=1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_km hpso_fm
t=1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_fm fcmeans
t=-0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_fm kmeans
t=3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm cso_km
t=16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm cso_fm
t=12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm g_cso_km
t=20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm g_cso_fm
t=7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm cn_pso
t=0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_fm cn_pso_km
t=-1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
cn_pso_fm cn_pso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm hpso_km
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
cn_pso_fm hpso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km fcmeans
t=-0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_km kmeans
t=3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km cso_km
t=16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km cso_fm
t=12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km g_cso_km
t=20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km g_cso_fm
t=7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km cn_pso
t=0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_km cn_pso_km
t=-1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_km cn_pso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km hpso_km
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_km hpso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm fcmeans
t=-0.495, df=30, cv=1.697, p=0.624
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_fm kmeans
t=3.078, df=30, cv=1.697, p=0.004
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm cso_km
t=16.214, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm cso_fm
t=12.066, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm g_cso_km
t=20.772, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm g_cso_fm
t=7.968, df=30, cv=1.697, p=0.000
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm cn_pso
t=0.662, df=30, cv=1.697, p=0.513
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_fm cn_pso_km
t=-1.000, df=30, cv=1.697, p=0.325
Accept null hypothesis that the means are equal.
Accept null hypothesis that the means are equal.
hpso_fm cn_pso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm hpso_km
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.
hpso_fm hpso_fm
t=nan, df=30, cv=1.697, p=nan
Reject the null hypothesis that the means are equal.
Reject the null hypothesis that the means are equal.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in double_scalars

In [0]:
df2 = pd.DataFrame(d)
df2.columns = df.columns
df2.index = df.columns

In [9]:
df2

             fcmeans     kmeans     cso_km  ...  cn_pso_fm    hpso_km    hpso_fm
fcmeans     0.000000   2.518974  11.799624  ...   0.494984   0.494984   0.494984
kmeans     -2.518974   0.000000   9.327158  ...  -3.078349  -3.078349  -3.078349
cso_km    -11.799624  -9.327158   0.000000  ... -16.213674 -16.213674 -16.213674
cso_fm     -9.753641  -7.570885   0.616670  ... -12.066330 -12.066330 -12.066330
g_cso_km  -13.029470 -10.268493   0.196762  ... -20.771509 -20.771509 -20.771509
g_cso_fm   -6.866782  -4.884690   2.507608  ...  -7.967977  -7.967977  -7.967977
cn_pso     -0.770280   2.254490  13.401172  ...  -0.662266  -0.662266  -0.662266
cn_pso_km  -0.411090   3.150662  16.240922  ...   1.000000   1.000000   1.000000
cn_pso_fm  -0.494984   3.078349  16.213674  ...        NaN        NaN        NaN
hpso_km    -0.494984   3.078349  16.213674  ...        NaN        NaN        NaN
hpso_fm    -0.494984   3.078349  16.213674  ...        NaN        NaN        NaN

[11 rows x 11 columns]

In [15]:
d,l = [],[]
for i in df.columns:
  for j in df.columns:
    data1 = df[i].values
    data2 = df[j].values
    alpha = 0.05
    t_stat, val, cv, p = independent_ttest(data1, data2, alpha)
    l.append(p)
  d.append(l)
  l = []
d = np.array(d)
df3 = pd.DataFrame(d)
df3.columns = df.columns
df3.index = df.columns

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in double_scalars

In [16]:
df3

                fcmeans        kmeans  ...       hpso_km       hpso_fm
fcmeans    1.000000e+00  1.733259e-02  ...  6.242175e-01  6.242175e-01
kmeans     1.733259e-02  1.000000e+00  ...  4.421426e-03  4.421426e-03
cso_km     8.488765e-13  2.258342e-10  ...  2.220446e-16  2.220446e-16
cso_fm     8.152856e-11  1.925554e-08  ...  4.862777e-13  4.862777e-13
g_cso_km   6.949996e-14  2.459610e-11  ...  0.000000e+00  0.000000e+00
g_cso_fm   1.273411e-07  3.225786e-05  ...  6.808021e-09  6.808021e-09
cn_pso     4.471576e-01  3.162387e-02  ...  5.128565e-01  5.128565e-01
cn_pso_km  6.839284e-01  3.676417e-03  ...  3.253086e-01  3.253086e-01
cn_pso_fm  6.242175e-01  4.421426e-03  ...           NaN           NaN
hpso_km    6.242175e-01  4.421426e-03  ...           NaN           NaN
hpso_fm    6.242175e-01  4.421426e-03  ...           NaN           NaN

[11 rows x 11 columns]